source "https://rubygems.org"

gem 'activesupport'
gem 'aubio', git: 'https://github.com/xavriley/ruby-aubio.git', branch: 'master'
gem 'fast_osc', '= 0.0.12'
gem 'ffi'
gem 'gettext'
gem 'hamster'
gem 'i18n'
gem 'kramdown'
gem 'locale'
gem 'multi_json'
gem 'memoist'
gem 'rubame'
gem 'rugged'
gem 'sys-proctable'
gem 'wavefile'

group :development, :test do
  gem 'mocha'
  gem 'minitest'
  gem 'test-unit'
end
